// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwdoU4I2FC_YhAtx6AU1IX-7BSHYpMWAY',
    appId: '1:147378754091:android:eecf29b1173bca0411106e',
    messagingSenderId: '147378754091',
    projectId: 'chat-app-830f1',
    storageBucket: 'chat-app-830f1.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCzURlk8Mwrbb0vCMsERI0qqDwAa9VA1s',
    appId: '1:147378754091:web:3cab5589149136db11106e',
    messagingSenderId: '147378754091',
    projectId: 'chat-app-830f1',
    authDomain: 'chat-app-830f1.firebaseapp.com',
    storageBucket: 'chat-app-830f1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Etn208QphueTFbnczjRnDnMf5JkMtlg',
    appId: '1:147378754091:ios:e813cee2846d0bd911106e',
    messagingSenderId: '147378754091',
    projectId: 'chat-app-830f1',
    storageBucket: 'chat-app-830f1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Etn208QphueTFbnczjRnDnMf5JkMtlg',
    appId: '1:147378754091:ios:e813cee2846d0bd911106e',
    messagingSenderId: '147378754091',
    projectId: 'chat-app-830f1',
    storageBucket: 'chat-app-830f1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCzURlk8Mwrbb0vCMsERI0qqDwAa9VA1s',
    appId: '1:147378754091:web:ad995bbf339574c911106e',
    messagingSenderId: '147378754091',
    projectId: 'chat-app-830f1',
    authDomain: 'chat-app-830f1.firebaseapp.com',
    storageBucket: 'chat-app-830f1.firebasestorage.app',
  );
}
